### PR TITLE
Added a view to create templates for future contests

### LINKED ISSUE #2154: Add a view to create templates for future contests
Users should be able to create their own custom contests.

### PR DESCRIPTION
**Pull request by Cheshiriks**
- added Create contest template view
- added button to go to the view

Closes #2154

### CODE REVIEW

**Review by kgevorkyan — COMMENTED** [review]
Why do we need to show the types of name, description and so on, on view?

**Comment by Cheshiriks** [comment]
> Why do we need to show the types of name, description and so on, on view?

On this view, the user specifies which fields to fill in future contests and chooses what type they should be.

**Comment by kgevorkyan** [comment]
> Member

I think
`name` = `str`
`descr` = `text`
should be enough, isn't it?

if not, may be we can create aliases on frontend? pure types like `MULTI_STRING` are very ugly

and by the way, why is critial = `num`? shouldn't it be `bool`?

**Comment by Cheshiriks** [comment]
> > Member
> 
> I think `name` = `str` `descr` = `text` should be enough, isn't it?
> 
> if not, may be we can create aliases on frontend? pure types like `MULTI_STRING` are very ugly
> 
> and by the way, why is critial = `num`? shouldn't it be `bool`?

Added pretty name

**Review by kgevorkyan — APPROVED** [review]

**Pull request merged**
