### PR TITLE
Replace `Vulnerability` by COSV

### LINKED ISSUE #2506: Replace `com.saveourtool.save.entities.vulnerabilities.Vulnerability`  by `com.saveourtool.osv4k.OsvSchema`

### LINKED ISSUE #2521: Reduce usage of `VulnerabilityDto` in controller

### PR DESCRIPTION
**Pull request by nulls**
### What's done:
- re-used `CosvMetadata` and `RawOsvSchema` on FE to display info about Vulnerability
- removed `vulnerability` table

It closes #2506

### CODE REVIEW

**Comment by nulls** [comment]
let's rename it to `VulnerabilityNew`. It will replace `Vulnerability` and `VulnerabilityDto` in future

**Comment by nulls** [comment]
Test data can be returned after #2557

**Comment by nulls** [comment]
> Test data can be returned after #2557

done

**Comment by nulls** [comment]
need to add JsonSerializer for `TimeLine` in COSV

**Review by sanyavertolet — APPROVED** [review]
lgtm

**Comment by nulls** [comment]
Discussed offline: need to support Submitted date type on metadata level

**Pull request merged**
