### PR TITLE
Removed flaky tests from frontend

### PR DESCRIPTION
**Pull request by sanyavertolet**
### What's done:
 * Removed ParsePositionStringTest.kt with flaky frontend tests

### CODE REVIEW

**Review by Cheshiriks — APPROVED** [review]

**Comment by kgevorkyan** [comment]
nice approach to fix test - just remove it 👍🤣

**Comment by sanyavertolet** [comment]
> nice approach to fix test - just remove it 👍🤣

Frontend tests kill me. A lot of time should be spent in order to work it out. I guess we have an issue for FE tests. For now it might be a better idea to remove it.

**Comment by akuleshov7** [comment]
> > nice approach to fix test - just remove it 👍🤣
> 
> 
> 
> Frontend tests kill me. A lot of time should be spent in order to work it out. I guess we have an issue for FE tests. For now it might be a better idea to remove it.


Agree

**Comment by kgevorkyan** [comment]
I meant, that it could be just ignored
but nevermind

**Pull request merged**
