### PR TITLE
FossGraphView improvements

### PR DESCRIPTION
**Pull request by sanyavertolet**
### What's done:
 * Reworked card with brief info
 * Moved tables on info tab
 * Added clickable placeholder for table

### TODO:
 * Fix ugly comments

### How it looks:

https://github.com/saveourtool/save-cloud/assets/35039155/3bd27904-ba7d-4f22-8401-c60925be7dc3

#### upd:
screenshot

### CODE REVIEW

**Comment by akuleshov7** [comment]
Make a boarder dotted line: https://hcdev.ru/css/border-bottom-style/

**Comment by akuleshov7** [comment]
Make a PLUS bigger

**Review by akuleshov7 — APPROVED** [review]
Lgtm, hope will not be merged automatically

**Comment by Cheshiriks** [comment]
Can the project type be filled in automatically and not allowed to be changed?

**Review by Cheshiriks — APPROVED** [review]
Can the project type be filled in automatically and not allowed to be changed?

**Comment by sanyavertolet** [comment]
> Can the project type be filled in automatically and not allowed to be changed?

Will be done later as some components should be reworked

**Pull request merged**
