### PR TITLE
Migrate `DependencyStorage` to `SuspendingStorage`

### LINKED ISSUE #1898: Migrate `Demo` to coroutines storage

### PR DESCRIPTION
**Pull request by nulls**
### What's done:
- added `StorageCoroutines` and implementations for it
- added `AbstractSuspendingStorage`
- migrated `DependencyStorage` to `SuspendingStorage`

It closes #1898

### CODE REVIEW

**Comment by sanyavertolet** [comment]
@nulls will it ever be merged? suggestion to close this PR due to many conflicts

**Comment by nulls** [comment]
> @nulls will it ever be merged?

The PR was created to demonstrate a new API for storages and a way to avoid casting from mono to deferred and back.

Will close if it's bother you, don't have time for `demo` now

**Comment by sanyavertolet** [comment]
> > @nulls will it ever be merged?
> 
> The PR was created to demonstrate a new API for storages and a way to avoid casting from mono to deferred and back.
> 
> Will close if it's bother you, don't have time for `demo` now

I mean, it seems to have a lot of merge conflicts. Do you think it is easier to fix those conflicts or better start from the very beginning?

**Comment by nulls** [comment]
> Do you think it is easier to fix those conflicts or better start from the very beginning?

I looked, right now it's better to resolve conflicts: there are not so big

**Pull request closed without merging**
