### PR TITLE
Add ability to change confirm type for admins

### PR DESCRIPTION
**Pull request by kgevorkyan**
Capture

### CODE REVIEW

**Comment by nulls** [comment]
@akuleshov7, will we update confirm type manually or it should be automated?

**Review by nulls — APPROVED** [review]

**Review by DrAlexD — APPROVED** [review]

**Comment by akuleshov7** [comment]
Hm, interesting. But why does user can select it?

**Review by akuleshov7 — CHANGES_REQUESTED** [review]
Are you sure, that someone can edit it?

**Comment by kgevorkyan** [comment]
> Are you sure, that someone can edit it?

probably. if we allow admins to change all other fields, this could be changed by admins manually too

**Comment by akuleshov7** [comment]
For admins only?

**Review by akuleshov7 — APPROVED** [review]

**Pull request merged**
