### PR TITLE
okio-extras

### PR DESCRIPTION
**Pull request by sanyavertolet**
### What's done:
 * Added `saveourtool/okio-extras` to `settings.gradle.kts`

#### See also:
https://github.com/saveourtool/save-cli/commit/67267e58aff886359a9461b2da21a0b998e4bb80

### CODE REVIEW

**Comment by sanyavertolet** [comment]
@0x6675636b796f75676974687562 
telegram-cloud-photo-size-2-5469822743777231414-y

**Comment by sanyavertolet** [comment]
https://scans.gradle.com/s/seosg3ubpcuyw/failure#1

**Review by akuleshov7 — APPROVED** [review]

**Comment by 0x6675636b796f75676974687562** [comment]
The cause of the problem is that both `save-cli` **0.3.7** and the newly-released `save-cli` **0.3.8** depend on the snapshot version of `sarif-utils` (**0.2.0-SNAPSHOT**), and the latest snapshot version now depends on `okio-extras`.

So, from the standpoint of `:save-agent`, the versions _haven't_ changed but the dependencies _have_.

**Comment by kgevorkyan** [comment]
@sanyavertolet `save-cli` 0.3.8 released, so you can change `lib.versions` and retry

**Review by 0x6675636b796f75676974687562 — APPROVED** [review]

**Comment by 0x6675636b796f75676974687562** [comment]
The build seems to pass (at least, locally).

Yet, I suggest we switch to the **released** `sarif-utils` version in `save-cli`: saveourtool/save-cli#507.

**Pull request merged**
