### PR TITLE
react-sigma support

### PR DESCRIPTION
**Pull request by sanyavertolet**
### What's done:
 * Added kotlin wrapper for `useLoadGraph` hook from `@react-sigma/core`
 * Added kotlin wrapper for `sigmaContainer` FC from `@react-sigma/core`

### Example
1. Define graph-loader `VFC`
```Kotlin
private val loadGraph = VFC {
    val loadGraphCallback = useLoadGraph()
    useEffect(loadGraphCallback) {
        loadGraphCallback(js(" { attributes: {name: 'My Graph'}, nodes: [{key: 'Thomas'}, {key: 'Eric'}], edges: [{source: 'Thomas', target: 'Eric'}] }"))
    }
}
```
2. Use `sigmaContainer` with graph loader (do not forget to put `css`)
```Kotlin
kotlinext.js.require("@react-sigma/core/lib/react-sigma.min.css")
sigmaContainer {
    style = jso {
        height = "500px"
        width = "500px"
    }
    loadGraph()
}
```

### Todo:
In order to make this code work we need to add some layout in order to make sigma place the nodes (assign `x` and `y` coordinates to each node)

### [Link to documentation](https://sim51.github.io/react-sigma/docs/api)

### CODE REVIEW

**Comment by petertrr** [comment]
> `loadGraphCallback(js(" { attributes: {name: 'My Graph'}, nodes: [{key: 'Thomas'}, {key: 'Eric'}], edges: [{source: 'Thomas', target: 'Eric'}] }"))`

I think that even with dynamic typing it can be expressed with a `jso {}` instead of `js()` wrapping a JSON, can't it?

Also, we are directing everything cpg-demo related into `feature/neo4j4cpg` branch and not into master.

**Comment by nulls** [comment]
> ` { attributes: {name: 'My Graph'}, nodes: [{key: 'Thomas'}, {key: 'Eric'}], edges: [{source: 'Thomas', target: 'Eric'}] }`

Is it a JSON?

Also maybe introduce DTO class:
```kotlin
data class Content(
    val attributes: Attributes,
    val nodes: List<Node>,
    val edges: List<Edge>,
)

data class Attributes(
    val name: String,
)

data class Node(
    val key: String,
)

data class Edge(
    val source: String,
    val target: String,
)
```

**Comment by sanyavertolet** [comment]
> > `{ attributes: {name: 'My Graph'}, nodes: [{key: 'Thomas'}, {key: 'Eric'}], edges: [{source: 'Thomas', target: 'Eric'}] }`
> 
> Is it a JSON?
> 
> Also maybe introduce DTO class:
> 
> ```kotlin
> data class Content(
>     val attributes: Attributes,
>     val nodes: List<Node>,
>     val edges: List<Edge>,
> )
> 
> data class Attributes(
>     val name: String,
> )
> 
> data class Node(
>     val key: String,
> )
> 
> data class Edge(
>     val source: String,
>     val target: String,
> )
> ```

I discussed the idea of DTOs with you offline yesterday and you told me that for phase 1 we do not need those DTOs

**Comment by nulls** [comment]
> for phase 1 we do not need those DTOs

then in phase 2 :)

**Review by nulls — APPROVED** [review]

**Pull request merged**
